export class ReferenceData {
    COUNTRIES  = [
        {description: 'Afghanistan', id: 'AF'},
        {description: 'Åland Islands', id: 'AX'},
        {description: 'Albania', id: 'AL'},
        {description: 'Algeria', id: 'DZ'},
        {description: 'American Samoa', id: 'AS'},
        {description: 'AndorrA', id: 'AD'},
        {description: 'Angola', id: 'AO'},
        {description: 'Anguilla', id: 'AI'},
        {description: 'Antarctica', id: 'AQ'},
        {description: 'Antigua and Barbuda', id: 'AG'},
        {description: 'Argentina', id: 'AR'},
        {description: 'Armenia', id: 'AM'},
        {description: 'Aruba', id: 'AW'},
        {description: 'Australia', id: 'AU'},
        {description: 'Austria', id: 'AT'},
        {description: 'Azerbaijan', id: 'AZ'},
        {description: 'Bahamas', id: 'BS'},
        {description: 'Bahrain', id: 'BH'},
        {description: 'Bangladesh', id: 'BD'},
        {description: 'Barbados', id: 'BB'},
        {description: 'Belarus', id: 'BY'},
        {description: 'Belgium', id: 'BE'},
        {description: 'Belize', id: 'BZ'},
        {description: 'Benin', id: 'BJ'},
        {description: 'Bermuda', id: 'BM'},
        {description: 'Bhutan', id: 'BT'},
        {description: 'Bolivia', id: 'BO'},
        {description: 'Bosnia and Herzegovina', id: 'BA'},
        {description: 'Botswana', id: 'BW'},
        {description: 'Bouvet Island', id: 'BV'},
        {description: 'Brazil', id: 'BR'},
        {description: 'British Indian Ocean Territory', id: 'IO'},
        {description: 'Brunei Darussalam', id: 'BN'},
        {description: 'Bulgaria', id: 'BG'},
        {description: 'Burkina Faso', id: 'BF'},
        {description: 'Burundi', id: 'BI'},
        {description: 'Cambodia', id: 'KH'},
        {description: 'Cameroon', id: 'CM'},
        {description: 'Canada', id: 'CA'},
        {description: 'Cape Verde', id: 'CV'},
        {description: 'Cayman Islands', id: 'KY'},
        {description: 'Central African Republic', id: 'CF'},
        {description: 'Chad', id: 'TD'},
        {description: 'Chile', id: 'CL'},
        {description: 'China', id: 'CN'},
        {description: 'Christmas Island', id: 'CX'},
        {description: 'Cocos (Keeling) Islands', id: 'CC'},
        {description: 'Colombia', id: 'CO'},
        {description: 'Comoros', id: 'KM'},
        {description: 'Congo', id: 'CG'},
        {description: 'Congo, The Democratic Republic of the', id: 'CD'},
        {description: 'Cook Islands', id: 'CK'},
        {description: 'Costa Rica', id: 'CR'},
        {description: 'Cote D\'Ivoire', id: 'CI'},
        {description: 'Croatia', id: 'HR'},
        {description: 'Cuba', id: 'CU'},
        {description: 'Cyprus', id: 'CY'},
        {description: 'Czech Republic', id: 'CZ'},
        {description: 'Denmark', id: 'DK'},
        {description: 'Djibouti', id: 'DJ'},
        {description: 'Dominica', id: 'DM'},
        {description: 'Dominican Republic', id: 'DO'},
        {description: 'Ecuador', id: 'EC'},
        {description: 'Egypt', id: 'EG'},
        {description: 'El Salvador', id: 'SV'},
        {description: 'Equatorial Guinea', id: 'GQ'},
        {description: 'Eritrea', id: 'ER'},
        {description: 'Estonia', id: 'EE'},
        {description: 'Ethiopia', id: 'ET'},
        {description: 'Falkland Islands (Malvinas)', id: 'FK'},
        {description: 'Faroe Islands', id: 'FO'},
        {description: 'Fiji', id: 'FJ'},
        {description: 'Finland', id: 'FI'},
        {description: 'France', id: 'FR'},
        {description: 'French Guiana', id: 'GF'},
        {description: 'French Polynesia', id: 'PF'},
        {description: 'French Southern Territories', id: 'TF'},
        {description: 'Gabon', id: 'GA'},
        {description: 'Gambia', id: 'GM'},
        {description: 'Georgia', id: 'GE'},
        {description: 'Germany', id: 'DE'},
        {description: 'Ghana', id: 'GH'},
        {description: 'Gibraltar', id: 'GI'},
        {description: 'Greece', id: 'GR'},
        {description: 'Greenland', id: 'GL'},
        {description: 'Grenada', id: 'GD'},
        {description: 'Guadeloupe', id: 'GP'},
        {description: 'Guam', id: 'GU'},
        {description: 'Guatemala', id: 'GT'},
        {description: 'Guernsey', id: 'GG'},
        {description: 'Guinea', id: 'GN'},
        {description: 'Guinea-Bissau', id: 'GW'},
        {description: 'Guyana', id: 'GY'},
        {description: 'Haiti', id: 'HT'},
        {description: 'Heard Island and Mcdonald Islands', id: 'HM'},
        {description: 'Holy See (Vatican City State)', id: 'VA'},
        {description: 'Honduras', id: 'HN'},
        {description: 'Hong Kong', id: 'HK'},
        {description: 'Hungary', id: 'HU'},
        {description: 'Iceland', id: 'IS'},
        {description: 'India', id: 'IN'},
        {description: 'Indonesia', id: 'ID'},
        {description: 'Iran, Islamic Republic Of', id: 'IR'},
        {description: 'Iraq', id: 'IQ'},
        {description: 'Ireland', id: 'IE'},
        {description: 'Isle of Man', id: 'IM'},
        {description: 'Israel', id: 'IL'},
        {description: 'Italy', id: 'IT'},
        {description: 'Jamaica', id: 'JM'},
        {description: 'Japan', id: 'JP'},
        {description: 'Jersey', id: 'JE'},
        {description: 'Jordan', id: 'JO'},
        {description: 'Kazakhstan', id: 'KZ'},
        {description: 'Kenya', id: 'KE'},
        {description: 'Kiribati', id: 'KI'},
        {description: 'Korea, Democratic People\'S Republic of', id: 'KP'},
        {description: 'Korea, Republic of', id: 'KR'},
        {description: 'Kuwait', id: 'KW'},
        {description: 'Kyrgyzstan', id: 'KG'},
        {description: 'Lao People\'S Democratic Republic', id: 'LA'},
        {description: 'Latvia', id: 'LV'},
        {description: 'Lebanon', id: 'LB'},
        {description: 'Lesotho', id: 'LS'},
        {description: 'Liberia', id: 'LR'},
        {description: 'Libyan Arab Jamahiriya', id: 'LY'},
        {description: 'Liechtenstein', id: 'LI'},
        {description: 'Lithuania', id: 'LT'},
        {description: 'Luxembourg', id: 'LU'},
        {description: 'Macao', id: 'MO'},
        {description: 'Macedonia, The Former Yugoslav Republic of', id: 'MK'},
        {description: 'Madagascar', id: 'MG'},
        {description: 'Malawi', id: 'MW'},
        {description: 'Malaysia', id: 'MY'},
        {description: 'Maldives', id: 'MV'},
        {description: 'Mali', id: 'ML'},
        {description: 'Malta', id: 'MT'},
        {description: 'Marshall Islands', id: 'MH'},
        {description: 'Martinique', id: 'MQ'},
        {description: 'Mauritania', id: 'MR'},
        {description: 'Mauritius', id: 'MU'},
        {description: 'Mayotte', id: 'YT'},
        {description: 'Mexico', id: 'MX'},
        {description: 'Micronesia, Federated States of', id: 'FM'},
        {description: 'Moldova, Republic of', id: 'MD'},
        {description: 'Monaco', id: 'MC'},
        {description: 'Mongolia', id: 'MN'},
        {description: 'Montserrat', id: 'MS'},
        {description: 'Morocco', id: 'MA'},
        {description: 'Mozambique', id: 'MZ'},
        {description: 'Myanmar', id: 'MM'},
        {description: 'Namibia', id: 'NA'},
        {description: 'Nauru', id: 'NR'},
        {description: 'Nepal', id: 'NP'},
        {description: 'Netherlands', id: 'NL'},
        {description: 'Netherlands Antilles', id: 'AN'},
        {description: 'New Caledonia', id: 'NC'},
        {description: 'New Zealand', id: 'NZ'},
        {description: 'Nicaragua', id: 'NI'},
        {description: 'Niger', id: 'NE'},
        {description: 'Nigeria', id: 'NG'},
        {description: 'Niue', id: 'NU'},
        {description: 'Norfolk Island', id: 'NF'},
        {description: 'Northern Mariana Islands', id: 'MP'},
        {description: 'Norway', id: 'NO'},
        {description: 'Oman', id: 'OM'},
        {description: 'Pakistan', id: 'PK'},
        {description: 'Palau', id: 'PW'},
        {description: 'Palestinian Territory, Occupied', id: 'PS'},
        {description: 'Panama', id: 'PA'},
        {description: 'Papua New Guinea', id: 'PG'},
        {description: 'Paraguay', id: 'PY'},
        {description: 'Peru', id: 'PE'},
        {description: 'Philippines', id: 'PH'},
        {description: 'Pitcairn', id: 'PN'},
        {description: 'Poland', id: 'PL'},
        {description: 'Portugal', id: 'PT'},
        {description: 'Puerto Rico', id: 'PR'},
        {description: 'Qatar', id: 'QA'},
        {description: 'Reunion', id: 'RE'},
        {description: 'Romania', id: 'RO'},
        {description: 'Russian Federation', id: 'RU'},
        {description: 'RWANDA', id: 'RW'},
        {description: 'Saint Helena', id: 'SH'},
        {description: 'Saint Kitts and Nevis', id: 'KN'},
        {description: 'Saint Lucia', id: 'LC'},
        {description: 'Saint Pierre and Miquelon', id: 'PM'},
        {description: 'Saint Vincent and the Grenadines', id: 'VC'},
        {description: 'Samoa', id: 'WS'},
        {description: 'San Marino', id: 'SM'},
        {description: 'Sao Tome and Principe', id: 'ST'},
        {description: 'Saudi Arabia', id: 'SA'},
        {description: 'Senegal', id: 'SN'},
        {description: 'Serbia and Montenegro', id: 'CS'},
        {description: 'Seychelles', id: 'SC'},
        {description: 'Sierra Leone', id: 'SL'},
        {description: 'Singapore', id: 'SG'},
        {description: 'Slovakia', id: 'SK'},
        {description: 'Slovenia', id: 'SI'},
        {description: 'Solomon Islands', id: 'SB'},
        {description: 'Somalia', id: 'SO'},
        {description: 'South Africa', id: 'ZA'},
        {description: 'South Georgia and the South Sandwich Islands', id: 'GS'},
        {description: 'Spain', id: 'ES'},
        {description: 'Sri Lanka', id: 'LK'},
        {description: 'Sudan', id: 'SD'},
        {description: 'Suridescription', id: 'SR'},
        {description: 'Svalbard and Jan Mayen', id: 'SJ'},
        {description: 'Swaziland', id: 'SZ'},
        {description: 'Sweden', id: 'SE'},
        {description: 'Switzerland', id: 'CH'},
        {description: 'Syrian Arab Republic', id: 'SY'},
        {description: 'Taiwan, Province of China', id: 'TW'},
        {description: 'Tajikistan', id: 'TJ'},
        {description: 'Tanzania, United Republic of', id: 'TZ'},
        {description: 'Thailand', id: 'TH'},
        {description: 'Timor-Leste', id: 'TL'},
        {description: 'Togo', id: 'TG'},
        {description: 'Tokelau', id: 'TK'},
        {description: 'Tonga', id: 'TO'},
        {description: 'Trinidad and Tobago', id: 'TT'},
        {description: 'Tunisia', id: 'TN'},
        {description: 'Turkey', id: 'TR'},
        {description: 'Turkmenistan', id: 'TM'},
        {description: 'Turks and Caicos Islands', id: 'TC'},
        {description: 'Tuvalu', id: 'TV'},
        {description: 'Uganda', id: 'UG'},
        {description: 'Ukraine', id: 'UA'},
        {description: 'United Arab Emirates', id: 'AE'},
        {description: 'United Kingdom', id: 'GB'},
        {description: 'United States', id: 'US'},
        {description: 'United States Minor Outlying Islands', id: 'UM'},
        {description: 'Uruguay', id: 'UY'},
        {description: 'Uzbekistan', id: 'UZ'},
        {description: 'Vanuatu', id: 'VU'},
        {description: 'Venezuela', id: 'VE'},
        {description: 'Viet Nam', id: 'VN'},
        {description: 'Virgin Islands, British', id: 'VG'},
        {description: 'Virgin Islands, U.S.', id: 'VI'},
        {description: 'Wallis and Futuna', id: 'WF'},
        {description: 'Western Sahara', id: 'EH'},
        {description: 'Yemen', id: 'YE'},
        {description: 'Zambia', id: 'ZM'},
        {description: 'Zimbabwe', id: 'ZW'}
    ];
}
